### ISSUE TITLE
Can´t Update Base Table or view not found.

### ISSUE THREAD

**Issue by JPRuehmann** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#74]
If I try
`sudo php setup.php --update`
I get
```
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'Tine20.tine20_application_states' doesn't exist in /var/www/html/Tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /var/www/html/Tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/www/html/Tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/www/html/Tine20/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /var/www/html/Tine20/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `tine20_...', Array)
#4 /var/www/html/Tine20/vendor/zendframework/zendframework1/library/Zend/Db/Select.php(711): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select))
#5 /var/www/html/Tine20/Tinebase/Application.php(524): Zend_D in /var/www/html/Tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php on line 235

Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'Tine20.tine20_application_states' doesn't exist in /var/www/html/Tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /var/www/html/Tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/www/html/Tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/www/html/Tine20/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /var/www/html/Tine20/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `tine20_...', Array)
#4 /var/www/html/Tine20/vendor/zendframework/zendframework1/library/Zend/Db/Select.php(711): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select))
#5 /var/www/html/Tine20/Tinebase/Application.php(524): Zend_D in /var/www/html/Tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php on line 235
```
How do I make it work?
Thanks,

**Comment by pschuele** [comment]
ah, i think you are trying to update from 2017.08.XX to 2018.02.5.

you need to update to the latest 2017.08 (2017.08.11 - get it from here: http://packages.tine20.org/source/2017.08.11/) first.

**Comment by JPRuehmann** [comment]
That did not Help.
same as before.

**Comment by pschuele** [comment]
which one is your current version?
maybe you need to update to 2017.02.5( http://packages.tine20.org/source/2017.02.5/) first.

current version -> 2017.02.5 -> 2017.08.11 -> 2018.02.5

**Comment by JPRuehmann** [comment]
the 5.2.17 works (update) but the 1.8.17 not.

**Comment by JPRuehmann** [comment]
Is there a Way to Upgrade to a newer Version than 5.2.17?
Thanks,

**Comment by pschuele** [comment]
did you try the update from 2017.02.5 to 2017.08.1 (or 2017.08.11)? if yes: which error occurs?

**Comment by JPRuehmann** [comment]
Both the error in the first post.
I have no Voipmanager.

**Comment by pschuele** [comment]
ok - will try to reproduce the problem.

**Comment by JPRuehmann** [comment]
By the Way,
It updated without errors but a bunch of things are not working anymore after the Update to 05.02.2017.
Such as owncloud and the user View as Admin and some other.
They all throw the Errors from #77

**Comment by pschuele** [comment]
problem should be solved. you could use the updated Setup/Controller.php (https://github.com/tine20/Tine-2.0-Open-Source-Groupware-and-CRM/blob/8b367aed9d2109ba7f8b6b055650d80ec7705326/tine20/Setup/Controller.php) and try the update again. please tell us, if it works.

**Comment by JPRuehmann** [comment]
Still not working

With the nrew Controller.php setup.php throws the following,

`Der Server kann Ihre Anfrage leider Aufgrund einer temporären Überlastung, Wartungsarbeiten oder Fehlkonfiguration nicht beantworten. Bitte versuchen Sie es später noch einmal oder kontaktieren Sie Ihren Administrator.`

**Comment by JPRuehmann** [comment]
And now I Can´t Administer Tine anymore.
Login OK but no administrative functions anymore.

**Comment by JPRuehmann** [comment]
Now it works, I hope that is not happening every time I have to update.

All Data is lost in this way.
I had to deinstall all Apps in the old Version (1.2.17), delete the contents of the Tine20 Folder (except the config.inc.php File) then Copy the new Version to the Tine20 Folder, set the Rights for the Folder an its contents. and completely setup everything anew.

Thanks,

**Comment by pschuele** [comment]
> Fatal error: Uncaught Error: Undefined class constant 'FOLDER_TYPE_PERSONAL'

i think, your installation got messed up somehow. it is always better to remove the existing installation files (or use a symlink / the deb-package) to make sure you have the new code.

i also forgot to mention, that you need another fix to make the update work: https://github.com/tine20/Tine-2.0-Open-Source-Groupware-and-CRM/commit/76b988caadbfab4c539ff66eb611c64771ad6c18

I hope that this broken update was an exception and I'm sorry for the inconvenience!

**Comment by freisei** [comment]
Same Problem here. Updated Controller.php togehter with "Release11-Typo-Correction" works.

**Comment by pschuele** [comment]
ok, thanks for the update. we'll build a new release with the fixes today.
