### ISSUE TITLE
Base table or view not found - Update 

### ISSUE THREAD

**Issue by mrHJS** [tine20/Tine-2.0-Open-Source-Groupware-and-CRM#77]
Hello,
when I try to update from 2018.02 to 2018.05 using the update function in setup.php, I can update all the application to version 12.0, except for

Addressbook
Calendar

Felamimail

When I try to update Addressbook and Calendar I get the following error and don't know how to solve it.  
When I try to update Felamimail I get an error telling me that the server is working too much so that the action can't be down (although the server is doing nothing)...

Can you help me out?

```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'tine.tine20_application_states' doesn't exist, query was: SELECT `tine20_application_states`.`state` FROM `tine20_application_states` WHERE (`id` = '2f139ce99c1fe646556c678cda573b2540be8f93' AND `name` = 'filesystemRootSize') FOR UPDATE

.../vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute()
.../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute()
.../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query()
.../vendor/zendframework/zendframework1/library/Zend/Db/Select.php(711): Zend_Db_Adapter_Pdo_Abstract->query()
.../Tinebase/Application.php(524): Zend_Db_Select->query()
.../Tinebase/FileSystem.php(1041): Tinebase_Application->getApplicationState()
.../Tinebase/FileSystem.php(594): Tinebase_FileSystem->acquireWriteLock()
.../Setup/Controller.php(1957): Tinebase_FileSystem->fclose()
.../Addressbook/Setup/Update/Release11.php(164): Setup_Controller->createImportExportDefinitions()
.../Setup/Controller.php(598): Addressbook_Setup_Update_Release11->update_9()
.../Setup/Controller.php(488): Setup_Controller->updateApplication()
.../Setup/Frontend/Json.php(120): Setup_Controller->updateApplications()
.../vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Setup_Frontend_Json->updateApplications()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract->_dispatch()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server->_handle()
.../Setup/Server/Json.php(90): Zend_Json_Server->handle()
.../Setup/Core.php(115): Setup_Server_Json->handle()
.../setup.php(14): Setup_Core::dispatchRequest()
```

**Comment by eitschpione** [comment]
Hello mrHJS

I got a similar problem with update from Version: 2017.08 (2017.08.11) - to version 2018.02.5. The hole setup is not running and following error appears:

argv is not available, because ini option 'register_argc_argv' is set Off

.../Tinebase/Setup/Update/Release10.php(2424): Zend_Console_Getopt->__construct()
.../Tinebase/Setup/Update/Release11.php(309): Tinebase_Setup_Update_Release10->update_53()
.../Setup/Controller.php(593): Tinebase_Setup_Update_Release11->update_16()
.../Setup/Controller.php(476): Setup_Controller->updateApplication()
.../Setup/Frontend/Json.php(120): Setup_Controller->updateApplications()
.../vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Setup_Frontend_Json->updateApplications()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract->_dispatch()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server->_handle()
.../Setup/Server/Json.php(90): Zend_Json_Server->handle()
.../Setup/Core.php(115): Setup_Server_Json->handle()
.../setup.php(14): Setup_Core::dispatchRequest()

Where is the "ini option 'register_argc_argv'" ? Seems that i need to set it to "on". Anyone a solution?
Thanks and best regards

**Comment by eitschpione** [comment]
Hello
Now ... is setup in the php.ini the register_argc_argv to "on" ... the error is now following:

illegal json data in response

starting upgrade ... {"error":{"code":-32000,"message":"Voipmanager\/Setup\/setup.xml not found. If application got renamed or deleted, re-run setup.php.","data":{"message":"Voipmanager\/Setup\/setup.xml not found. If application got renamed or deleted, re-run setup.php.","code":0,"appName":"Setup","title":"Exception ({0})","trace":[{"file":"...\/Setup\/Frontend\/Cli.php","line":309,"function":"getSetupXml","class":"Setup_Controller","type":"->"},{"file":"...\/Setup\/Frontend\/Cli.php","line":107,"function":"_upgradeMysql564","class":"Setup_Frontend_Cli","type":"->"},{"file":"...\/Tinebase\/Setup\/Update\/Release10.php","line":2425,"function":"handle","class":"Setup_Frontend_Cli","type":"->"},{"file":"...\/Tinebase\/Setup\/Update\/Release11.php","line":309,"function":"update_53","class":"Tinebase_Setup_Update_Release10","type":"->"},{"file":"...\/Setup\/Controller.php","line":593,"function":"update_16","class":"Tinebase_Setup_Update_Release11","type":"->"},{"file":"...\/Setup\/Controller.php","line":476,"function":"updateApplication","class":"Setup_Controller","type":"->"},{"file":"...\/Setup\/Frontend\/Json.php","line":120,"function":"updateApplications","class":"Setup_Controller","type":"->"},{"file":"...\/vendor\/zendframework\/zendframework1\/library\/Zend\/Server\/Abstract.php","line":232,"function":"updateApplications","class":"Setup_Frontend_Json","type":"->"},{"file":"...\/vendor\/zendframework\/zendframework1\/library\/Zend\/Json\/Server.php","line":590,"function":"_dispatch","class":"Zend_Server_Abstract","type":"->"},{"file":"...\/vendor\/zendframework\/zendframework1\/library\/Zend\/Json\/Server.php","line":197,"function":"_handle","class":"Zend_Json_Server","type":"->"},{"file":"...\/Setup\/Server\/Json.php","line":90,"function":"handle","class":"Zend_Json_Server","type":"->"},{"file":"...\/Setup\/Core.php","line":115,"function":"handle","class":"Setup_Server_Json","type":"->"},{"file":"...\/setup.php","line":14,"function":"dispatchRequest","class":"Setup_Core","type":"::"}]}},"id":"8","jsonrpc":"2.0"}

What do i have to delete in the database (@Voipmanager), that this error is no problem anymore?
Thanks to all for your support - eitschpione

**Comment by pschuele** [comment]
@mrHJS your issue seems to be a duplicate of #74 - you have to update to the latest 2017.08 (that would be 2017.08.11, i think) first.
@eitschpione you have to download the current version of the Voipmanager module and put it into you tine20 dir. or: uninstall the module it before running update. if you still have problems, please open a new issue.

**Comment by pschuele** [comment]
closing this as it is a duplicate of #74

**Comment by mrHJS** [comment]
@pschuele 
I don't think it is a duplicate of #74 because I was on 2018.02 before and not on that 2017.08. version...

**Comment by pschuele** [comment]
from which exact version are you trying to update to the current 2018.02.5? 2018.02.2? when you give us the version, we can try to reproduce the problem.

**Comment by mrHJS** [comment]
Exactly, I tried to update from 2018.02.2 to 2018.02.5 and get the aforementioned error - but only when trying to update Addressbooks or Calendars.
Felamimail does not work either, but I get a different error ("Server ausgelastet") - although there is nothing running on the server.

All the other applications did upgrade without problems (i.e. Tinebase etc.)

**Comment by zinopu** [comment]
Hi,

i have the exact same problem.
My update routine was 2017.02.5 -> 2017.08.1 -> 2017.08.11 -> 2018.02.1 -> 2018.02.2 -> 2018.02.3 (failed)

I updated with "allinonepackage" and every module at once.

Now the update failed with the following message:
```
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'tine20db.tine20_application_states' doesn't exist in /var/www/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /var/www/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/www/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/www/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /var/www/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `tine20_...', Array)
#4 /var/www/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Select.php(711): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select))
#5 /var/www/tine20/Tinebase/Application.php(514): Zend_Db_Select->query()
#6 /var/www/tin in /var/www/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php on line 235

Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'tine20db.tine20_application_states' doesn't exist in /var/www/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /var/www/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/www/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/www/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /var/www/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `tine20_...', Array)
#4 /var/www/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Select.php(711): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select))
#5 /var/www/tine20/Tinebase/Application.php(514): Zend_Db_Select->query()
#6 /var/www/tin in /var/www/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php on line 235

```

**Comment by pschuele** [comment]
ok, thanks for the info, @zinopu .

@paulmhh do you have an idea what the problem might be? the update should work that way!

**Comment by mrHJS** [comment]
I also tried to update at once first - however after a while I got the above mentioned error, so I tried to update one application at a time.

It's really annoying because I cannot login anymore because Tine is telling me that I need to update it - but I cannot.

**Comment by zinopu** [comment]
Hi,

i fixed my tine2.0 instance after the third try. First, i dropped the database/web and restored it from my backup. Every update process started with version 2017.02.5.

My successful update routine was 2017.02.5 -> 2017.08.1 -> 2017.08.11 -> 2018.02.1 -> 2018.02.2 -> 2018.02.4 - 2018.02.5.
Furthermore after every update i logged in with the admin account and a user account.  

I don't know if something is maybe broken in version "2018.02.3" or the login after every update did the job. I hope it helps.


I updated the applications by using the CLI.
-> php setup.php --update

Server configuration:
-> Ubuntu 16.04
-> php - 7.0.30-0ubuntu0.16.04.1
-> apache - 2.4.18-2ubuntu3.8

**Comment by paulmhh** [comment]
Hello,

the update from 2018.02.2 -> 2018.02.3 is broken and fails. But even after the failed update run, no database restore is required. Just install the most current package (at the time writing and tested with: 2018.02.5) and repeat the update process, it will work.

**Comment by mrHJS** [comment]
Any news here? What can I do? Can't use Tine anymore because it wants me to update the applications but I can't for the error I have.

**Comment by ktrub** [comment]
Hello,

I am getting the same update messages as @mrHJS while trying to update the instance.
 
The last update on our system (Debian Stretch, Mariadb-server 10.1.26, apache 2.4.25)   was successfully executed in march using the system package manager and the Setup-FrontEnd.

Yesterday after upgrading the package I started successfully updating first Tinebase using the Setup-FrontEnd. After that the updates of  
Addressbook
Calendar
Admin
Felamimail
Task   
failed with the message: 

>SQLSTATE[42S02]: Base table or view not found: 1146 Table 'tine20db.tine20_application_states' doesn't exist, query was: Sc FROM `tine20_application_states` WHERE (`id` = '<id>' AND `name` = 'filesystemRootSize') FOR UPDATE

I tried to update all the applications at once using the console: `php setup.php --update` and got the same message.

Then I reinstalled the newest package and unsuccessfully updated it with message:

> Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'tine20db.tine20_application_states' doesn't exist... 

Is there a workaround or script that generates the missing table?
At the moment I cannot update the installed instance working with the existing database.

Thank you for your support - ktrub

**Comment by paulmhh** [comment]
afaik there is no problem, read the previous messages. Always update to the first major version, do not make bigger jumps! This works:

2017.02.5 -> 2017.08.1 -> 2018.02.1 -> 2018.02.5

do not use 2018.02.3
do not spread FUD
make a proper report if something is not working, whats your upgrade path? DB / PHP version, keep it short please

**Comment by mrHJS** [comment]
Sorry, but you don't seem to understand the point. I upgraded to each and every single version from the above mentioned upgrade path, except that before jumping on 2018.02.5 I was on 2018.02.2.

So there is a problem and I am not the only one as you can tell from ktrub's message. 

What can I do now? I cannot lose all of my data and I cannot export them as I cannot login for Tine telling me I have to upgrade applications first. :-(

**Comment by pschuele** [comment]
i can confirm that the update from 2018.02.2 to 2018.02.5 is broken. we will fix that and/or provide a solution for that.

**Comment by pschuele** [comment]
problem should be solved. you could use the updated Setup/Controller.php (https://github.com/tine20/Tine-2.0-Open-Source-Groupware-and-CRM/blob/8b367aed9d2109ba7f8b6b055650d80ec7705326/tine20/Setup/Controller.php) and try the update again. please tell us, if it works.

**Comment by mrHJS** [comment]
Hi there,
I just copied the whole code from the updated Controller.php and put it into the Controller.php from 2018.08.05 and tried to update the remaining three applications (Addressbooks, Calendar and Felamimail), but still no luck, this time another error:

```
illegal json data in response

Fatal error: Uncaught Error: Class 'Tinebase_Setup_Update_Release11' not found in /volume1/web/tine/Setup/Controller.php:658 Stack trace: #0 /volume1/web/tine/Setup/Controller.php(567): Setup_Controller->_assertApplicationStatesTable() #1 /volume1/web/tine/Setup/Controller.php(488): Setup_Controller->updateApplication(Object(Tinebase_Model_Application), '11') #2 /volume1/web/tine/Setup/Frontend/Json.php(120): Setup_Controller->updateApplications(Object(Tinebase_Record_RecordSet)) #3 /volume1/web/tine/vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Setup_Frontend_Json->updateApplications(Array) #4 /volume1/web/tine/vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract->_dispatch(Object(Zend_Server_Method_Definition), Array) #5 /volume1/web/tine/vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server->_handle() #6 /volume1/web/tine/Setup/Server/Json.php(90): Zend_Json_Server->handle(Object(Zend_Json_Server_Request_Http)) #7 /vol in /volume1/web/tine/Setup/Controller.php on line 658 
```

**Comment by mrHJS** [comment]
In the meantime I tried it several times, but the fatal error (see above) remains. So the fix won't work. :-(

**Comment by mrHJS** [comment]
Why is this closed? The problem is not solved and a lot of other people still face the same issue:
#81

**Comment by pschuele** [comment]
please also use this fix: https://github.com/tine20/Tine-2.0-Open-Source-Groupware-and-CRM/commit/76b988caadbfab4c539ff66eb611c64771ad6c18

**Comment by mrHJS** [comment]
Using this fix worked for Calendar and Addressbook. Now only one problem persists:
I cannot update Felamimail. I get the following error:

> Der Server kann Ihre Anfrage leider Aufgrund einer temporären Überlastung, Wartungsarbeiten oder Fehlkonfiguration nicht beantworten. Bitte versuchen Sie es später noch einmal oder kontaktieren Sie Ihren Administrator.

However, the server isn't doing anything at the moment. It is a Synology Diskstation and there is nothing running. Do you have any idea why this happens?

**Comment by pschuele** [comment]
could you please check the tine20/webserver logs? there should be a more helpful error message there.

**Comment by mrHJS** [comment]
This is what is written into Tine's error log when I try to update it:

> 3f5b5 setupuser - 2018-06-04T08:14:05+00:00 ERR (3): Felamimail_Setup_Update_Release11::update_0::29 Could not open defaultForwarding.sieve file
> 3f5b5 setupuser - 2018-06-04T08:14:05+00:00 ERR (3): Setup_Controller::updateApplication::575 Could not open defaultForwarding.sieve file
> 3f5b5 setupuser - 2018-06-04T08:14:05+00:00 ERR (3): Setup_Controller::updateApplication::576 #0 /volume1/web/tine/Setup/Controller.php(571): Felamimail_Setup_Update_Release11->update_0()
> #1 /volume1/web/tine/Setup/Controller.php(469): Setup_Controller->updateApplication(Object(Tinebase_Model_Application), '11')
> #2 /volume1/web/tine/Setup/Frontend/Json.php(120): Setup_Controller->updateApplications(Object(Tinebase_Record_RecordSet))
> #3 /volume1/web/tine/vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Setup_Frontend_Json->updateApplications(Array)
> #4 /volume1/web/tine/vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract->_dispatch(Object(Zend_Server_Method_Definition), Array)
> #5 /volume1/web/tine/vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server->_handle()
> #6 /volume1/web/tine/Setup/Server/Json.php(90): Zend_Json_Server->handle(Object(Zend_Json_Server_Request_Http))
> #7 /volume1/web/tine/Setup/Core.php(115): Setup_Server_Json->handle()
> #8 /volume1/web/tine/setup.php(14): Setup_Core::dispatchRequest()
> #9 {main}
> 3f5b5 setupuser - 2018-06-04T08:14:05+00:00 ERR (3): Tinebase_Exception::logExceptionToLogger::133 Tinebase_Exception_Backend -> Could not open defaultForwarding.sieve file

**Comment by gio32** [comment]
Since I did an update before applying 76b988c I have several applications at version 12 now - this seems to cause problems: while web interactive calendar and adressbook work, I cannot get CalDAV / CardDAV to work -> PROPFIND results in 404. Any suggestions?

**Comment by gio32** [comment]
Hm. This seems to be https://forge.tine20.org/view.php?id=13862 - not directly related to this issue but severe.

**Comment by mrHJS** [comment]
Does my log give you any idea what could be wrong with Tine?

**Comment by pschuele** [comment]
> Does my log give you any idea what could be wrong with Tine?

should be fixed by https://github.com/tine20/Tine-2.0-Open-Source-Groupware-and-CRM/commit/34ec1d009b9b5d47de34f1a31788b475c8e88323

also see https://forge.tine20.org/view.php?id=13856

**Comment by mrHJS** [comment]
Thanks, I copied the code from GitHub to the files, but I still cannot update Felamimail. Almost the same error. This is what is written in the log file:

> 8b777 setupuser - 2018-06-07T04:09:16+00:00 ERR (3): Felamimail_Setup_Update_Release11::update_0::33 Could not open defaultForwarding.sieve file
> 8b777 setupuser - 2018-06-07T04:09:16+00:00 ERR (3): Setup_Controller::updateApplication::575 Could not open defaultForwarding.sieve file
> 8b777 setupuser - 2018-06-07T04:09:16+00:00 ERR (3): Setup_Controller::updateApplication::576 #0 /volume1/web/tine/Setup/Controller.php(571): Felamimail_Setup_Update_Release11->update_0()
> #1 /volume1/web/tine/Setup/Controller.php(469): Setup_Controller->updateApplication(Object(Tinebase_Model_Application), '11')
> #2 /volume1/web/tine/Setup/Frontend/Json.php(120): Setup_Controller->updateApplications(Object(Tinebase_Record_RecordSet))
> #3 /volume1/web/tine/vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Setup_Frontend_Json->updateApplications(Array)
> #4 /volume1/web/tine/vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract->_dispatch(Object(Zend_Server_Method_Definition), Array)
> #5 /volume1/web/tine/vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server->_handle()
> #6 /volume1/web/tine/Setup/Server/Json.php(90): Zend_Json_Server->handle(Object(Zend_Json_Server_Request_Http))
> #7 /volume1/web/tine/Setup/Core.php(115): Setup_Server_Json->handle()
> #8 /volume1/web/tine/setup.php(14): Setup_Core::dispatchRequest()
> #9 {main}
> 8b777 setupuser - 2018-06-07T04:09:16+00:00 ERR (3): Tinebase_Exception::logExceptionToLogger::133 Tinebase_Exception_Backend -> Could not open defaultForwarding.sieve file

**Comment by mrHJS** [comment]
Even with fix ebc8cb8 the problem persists :-((

> illegal json data in response
> Fatal error: Uncaught Error: Call to undefined method Felamimail_Setup_Update_Release11::update_1() in /volume1/web/tine/Setup/Controller.php:571 Stack trace: #0 /volume1/web/tine/Setup/Controller.php(469): Setup_Controller->updateApplication(Object(Tinebase_Model_Application), '11') #1 /volume1/web/tine/Setup/Frontend/Json.php(120): Setup_Controller->updateApplications(Object(Tinebase_Record_RecordSet)) #2 /volume1/web/tine/vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Setup_Frontend_Json->updateApplications(Array) #3 /volume1/web/tine/vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract->_dispatch(Object(Zend_Server_Method_Definition), Array) #4 /volume1/web/tine/vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server->_handle() #5 /volume1/web/tine/Setup/Server/Json.php(90): Zend_Json_Server->handle(Object(Zend_Json_Server_Request_Http)) #6 /volume1/web/tine/Setup/Core.php(115): Setup_Server_Json->handle() #7 /volume1/we in /volume1/web/tine/Setup/Controller.php on line 571

**Comment by pschuele** [comment]
did you try it with the new version 2018.02.6?

**Comment by mrHJS** [comment]
No, not yet but will do now...

**Comment by pschuele** [comment]
> With 2018.02.06 the update finally worked
ok - closing this issue.
